#!/bin/bash

printf "HTML... "
err=$(yarn run pug src/layout -o public -P 2>&1 >/dev/null)
if [ $? -eq 0 ]; then echo "✓"; else printf "\n$err\n"; exit 1; fi

printf "CSS... "
err=$(yarn run sass src/style/style.sass public/style.css 2>&1 >/dev/null)
if [ $? -eq 0 ]; then echo "✓"; else printf "\n$err\n"; exit 1; fi

printf "JS... "
err=$(yarn run tsc 2>&1 >/dev/null)
if [ $? -eq 0 ]; then echo "✓"; else printf "\n$err\n"; exit 1; fi
