#!/bin/bash

# Usage ./watch html|css|js

case $1 in
    'html')
        yarn run pug -w src/layout -o public -P ;;
    'css')
        yarn run sass --watch --no-source-map src/style/style.sass public/style.css ;;
    'js')
        yarn run tsc --watch ;;
esac