#!/usr/bin/env ruby

# Usage: ./clean

# --- 

src_path = `find src/module -type f`
gen_path = `find public/module -type f`

src = {}
gen = {}

src_path.each_line { |line|
    file = File.basename(line.strip!, ".ts")
    src[file] = nil
}

gen_path.each_line { |line|
    file = File.basename(line.strip!, ".js")
    gen[file] = nil
}

delete = []
gen.each_key { |file| delete.push(file) if !src.has_key?(file) }

args = delete.map { |file| "public/module/#{file}.js" }.join("")
cmd = "rm #{args}"

if delete.length > 0
    puts cmd
    `#{cmd}`
end
