#!/usr/bin/env ruby

# Usage: ./clean

# --- 

src_res = `find src/module -type f`
gen_res = `find public/module -type f`

src = {}
gen = {}

src_res.each_line do |line|
    file = File.basename(line.strip!, ".ts")
    src[file] = nil
end

gen_res.each_line do |line|
    file = File.basename(line.strip!, ".js")
    gen[file] = nil
end

delete = []
cmd = "rm -rf"

gen.each_key do |file|
    delete.push(file) if !src.has_key?(file)
end

delete.each do |file|
    cmd += " public/module/#{file}.js"
end

`#{cmd}` if delete.length > 0
