#!/usr/bin/env ruby

# Usage: ./loc

# ---

res = `find src/module public/script -type f | sort | xargs wc -l | head -n -1`

data = {}

max_len = 0
total = 0

res.each_line.with_index do |line, idx|
    str = line.split(" ")

    filename = File.basename(str[1])
    loc = str[0].to_i
    data[filename] = loc

    total += loc
    max_len = filename.length > max_len ? filename.length : max_len    
end

max_digits = total.to_s.length

data.each do |filename, loc|
    len = filename.length
    digits = loc.to_s.length
    print " " * (max_len-len), filename, " = ",  " " * (max_digits-digits), loc, "\n"
end

print "-" * (max_len+max_digits+3), " +\n"
print " " * (max_len-5), "total = ", total, "\n"
